
# version: "29.2.1"

services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s



  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception


  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception


volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wordpress


networks:
  inception:
    driver: bridge


